<?php
/**
 * @file
 * override_panopoly_widgets.features.features_overrides.inc
 */

/**
 * Implements hook_features_override_default_overrides().
 */
function override_panopoly_widgets_features_override_default_overrides() {
  // This code is only used for UI in features. Exported alters hooks do the magic.
  $overrides = array();

  // Exported overrides for: field
  $overrides["field.fieldable_panels_pane-basic_file-field_basic_file_file.field_instance|display|default|settings|linked_field"] = array(
    'advanced' => array(
      'class' => '',
      'rel' => '',
      'target' => '',
      'text' => '',
      'title' => '',
    ),
    'destination' => '',
    'linked' => 0,
  );
  $overrides["field.fieldable_panels_pane-basic_file-field_basic_file_text.field_instance|display|default|settings|linked_field"] = array(
    'advanced' => array(
      'class' => '',
      'rel' => '',
      'target' => '',
      'text' => '',
      'title' => '',
    ),
    'destination' => '',
    'linked' => 0,
  );
  $overrides["field.fieldable_panels_pane-image-field_basic_image_caption.field_instance|display|default|settings|linked_field"] = array(
    'advanced' => array(
      'class' => '',
      'rel' => '',
      'target' => '',
      'text' => '',
      'title' => '',
    ),
    'destination' => '',
    'linked' => 0,
  );
  $overrides["field.fieldable_panels_pane-image-field_basic_image_image.field_instance|display|default|settings|linked_field"] = array(
    'advanced' => array(
      'class' => '',
      'rel' => '',
      'target' => '',
      'text' => '',
      'title' => '',
    ),
    'destination' => '',
    'linked' => 0,
  );
  $overrides["field.fieldable_panels_pane-map-field_map_address.field_instance|display|default|settings|linked_field"] = array(
    'advanced' => array(
      'class' => '',
      'rel' => '',
      'target' => '',
      'text' => '',
      'title' => '',
    ),
    'destination' => '',
    'linked' => 0,
  );
  $overrides["field.fieldable_panels_pane-map-field_map_information.field_instance|display|default|settings|linked_field"] = array(
    'advanced' => array(
      'class' => '',
      'rel' => '',
      'target' => '',
      'text' => '',
      'title' => '',
    ),
    'destination' => '',
    'linked' => 0,
  );
  $overrides["field.fieldable_panels_pane-quick_links-field_quick_links_links.field_instance|display|default|settings|linked_field"] = array(
    'advanced' => array(
      'class' => '',
      'rel' => '',
      'target' => '',
      'text' => '',
      'title' => '',
    ),
    'destination' => '',
    'linked' => 0,
  );
  $overrides["field.fieldable_panels_pane-spotlight-field_basic_spotlight_items.field_instance|display|default|settings|linked_field"] = array(
    'advanced' => array(
      'class' => '',
      'rel' => '',
      'target' => '',
      'text' => '',
      'title' => '',
    ),
    'destination' => '',
    'linked' => 0,
  );
  $overrides["field.fieldable_panels_pane-table-field_basic_table_table.field_instance|display|default|settings|linked_field"] = array(
    'advanced' => array(
      'class' => '',
      'rel' => '',
      'target' => '',
      'text' => '',
      'title' => '',
    ),
    'destination' => '',
    'linked' => 0,
  );
  $overrides["field.fieldable_panels_pane-text-field_basic_text_text.field_instance|display|default|settings|linked_field"] = array(
    'advanced' => array(
      'class' => '',
      'rel' => '',
      'target' => '',
      'text' => '',
      'title' => '',
    ),
    'destination' => '',
    'linked' => 0,
  );
  $overrides["field.fieldable_panels_pane-video-field_video_file.field_instance|display|default|settings|linked_field"] = array(
    'advanced' => array(
      'class' => '',
      'rel' => '',
      'target' => '',
      'text' => '',
      'title' => '',
    ),
    'destination' => '',
    'linked' => 0,
  );

 return $overrides;
}
